name: Sync Backend to Hugging Face
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Crear un repo temporal para el Space
          mkdir hf_sync_dir
          
          # 1. Copiamos todo el contenido de backend (donde está el Dockerfile)
          cp -r backend/* hf_sync_dir/
          
          # 2. Copiamos el README principal a la raíz del Space para que sea el que se visualice
          cp README.md hf_sync_dir/README.md

          cd hf_sync_dir
          
          git init
          git checkout -b main
          git add .
          git commit -m "Sync version: ${{ github.sha }}"
          
          # Subida forzada al Space
          git remote add hf https://d4r005:$HF_TOKEN@huggingface.co/spaces/d4r005/SRIUC
          git push hf main --force
